Bring in kernel-headers from kk4.4 as they are now removed from platform
Add new header patch to makefiles as needed

Make sensor hal Clang compliant
    sensors/sensors.c:32:17: error: empty scalar initializer

Audio hal: implement new method in public interface
  AudioHardwareInterface::openOutputStreamWithFlags

Change-Id: I36bc3dc2ff32580661c67ddce7b7de886285b95a